routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/**
 * Weather group
 */
Route::group([
    'prefix' => 'weather',
    'as' => 'weather.'
], function () {
    Route::get('index', 'WeatherController@index');
});

/**
 * Order group
 */
Route::group([
    'prefix' => 'order',
    'as' => 'order.'
], function () {
    Route::get('list', 'OrderController@list')->name('get.list');
    Route::get('edit/{id}', 'OrderController@getEdit')->name('get.edit');
    Route::post('edit/{id}', 'OrderController@postEdit')->name('post.edit');
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\{HasMany, HasOne};
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * Class Order
 * @package App\Models
 */
class Order extends Model
{
    /** @var int */
    const ORDER_STATUS_NEW = 0;
    /** @var int */
    const ORDER_STATUS_CONFIRMED = 10;
    /** @var int */
    const ORDER_STATUS_COMPLETED = 20;

    /** @var string */
    const ORDER_TYPE_OVERDUE = 'overdue';
    /** @var string */
    const ORDER_TYPE_CURRENT = 'current';
    /** @var string */
    const ORDER_TYPE_NEW = 'new';
    /** @var string */
    const ORDER_TYPE_DONE = 'done';
    /** @var string */
    const ORDER_TYPE_ALL = 'all';

    /** @var int */
    const LIMIT = 50;

    /**
     * @return string[]
     */
    public static function getAvailableTypes()
    {
        return [
            self::ORDER_TYPE_OVERDUE,
            self::ORDER_TYPE_CURRENT,
            self::ORDER_TYPE_NEW,
            self::ORDER_TYPE_DONE,
            self::ORDER_TYPE_ALL,
        ];
    }

    /**
     * Get Available statuses
     *
     * @return int[]
     */
    public static function getAvailableStatuses()
    {
        return [
            self::ORDER_STATUS_NEW,
            self::ORDER_STATUS_CONFIRMED,
            self::ORDER_STATUS_COMPLETED,
        ];
    }

    /**
     * @param int $code
     * @return string
     */
    public static function getStatusNameByCode(int $code)
    {
        if (isset(self::getStatuses()[$code])) {
            return self::getStatuses()[$code];
        }

        return '';
    }

    /**
     * @return array
     */
    public static function getStatuses()
    {
        return [
            self::ORDER_STATUS_NEW => trans('order.statuses.new'),
            self::ORDER_STATUS_CONFIRMED => trans('order.statuses.confirmed'),
            self::ORDER_STATUS_COMPLETED => trans('order.statuses.completed'),
        ];
    }

    /**
     * @return Partner|HasOne|null
     */
    public function getPartner()
    {
        return $this->partner()->first();
    }

    /**
     * @return HasOne
     */
    public function partner()
    {
        return $this->hasOne(Partner::class, 'id', 'partner_id');
    }

    /**
     * @return Collection|OrderProduct[]
     */
    public function getOrderProducts()
    {
        return $this->orderProducts()->get()->keyBy('product_id');
    }

    /**
     * @return HasMany
     */
    public function orderProducts()
    {
        return $this->hasMany(OrderProduct::class, 'order_id', 'id');
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts()
    {
        return $this->products()->get();
    }

    /**
     * @return BelongsToMany
     */
    public function products()
    {
        return $this->belongsToMany(Product::class, 'order_products');
    }

}

app/Models/OrderProduct.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OrderProduct extends Model
{
    //
}

app/Models/Partner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Partner extends Model
{
    //
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Models/Vendor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Vendor extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/OrderController.php
<?php


namespace App\Http\Controllers;


use App\Models\Order;
use App\Services\Order\{EditService, GetByIdService, ListGetService};
use App\Services\Partner\ListGetService as PartnerListGetService;
use Illuminate\Contracts\View\Factory;
use Illuminate\Foundation\Application;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;

/**
 * Class OrderController
 * @package App\Http\Controllers
 */
class OrderController extends Controller
{
    /**
     * @param ListGetService $service
     * @return Factory|Application|View
     */
    public function list(ListGetService $service)
    {
        return view('order.index', [
            'records' => $service->get(),
        ]);
    }

    /**
     * @param $id
     * @param GetByIdService $service
     * @param PartnerListGetService $partnerListService
     * @return Factory|Application|View
     */
    public function getEdit($id,
                            GetByIdService $service,
                            PartnerListGetService $partnerListService)
    {
        /** @var Order $record */
        $record = $service->get($id);
        return view('order.edit', [
            'record' => $record,
            'partners' => $partnerListService->get()->pluck('name', 'id'),
            'orderProducts' => $record->getOrderProducts()->keyBy('product_id'),
            'statuses' => Order::getStatuses(),
        ]);
    }

    /**
     * @param int $id
     * @param EditService $service
     * @return Application|RedirectResponse|Redirector
     */
    public function postEdit(int $id, EditService $service)
    {
        $service->get($id);
        return redirect()->route('order.get.list');
    }
}

app/Http/Controllers/WeatherController.php
<?php


namespace App\Http\Controllers;

use App\Interfaces\WeatherServiceInterface;
use Illuminate\Contracts\View\Factory;
use Illuminate\Foundation\Application;
use Illuminate\View\View;

/**
 * Class WeatherController
 * @package App\Http\Controllers
 */
class WeatherController extends Controller
{
    /**
     * @param WeatherServiceInterface $weatherService
     * @return Factory|Application|View
     */
    public function index(WeatherServiceInterface $weatherService)
    {
        return view('weather.index', [
            'weather' => $weatherService->result()
        ]);
    }
}

resources/views/elements/order-type-link.blade.php
<a href="{{ route('order.get.list', ['type' => $type]) }}" title="{{ trans("order.types.$type") }}">{{ trans("order.types.$type") }}</a>

resources/views/order/edit.blade.php
<form action="{{ route('order.post.edit', ['id' => $record->id]) }}" method="post">
    <div class="form-group row">
        <label for="inputEmail" class="control-label">{{ trans('order.email') }}</label>
        <input id="inputEmail"
               name="client_email"
               type="email"
               class="form-control border-radius"
               placeholder="Email"
               value="@if(isset($record)){{ $record->client_email }}@else{{ Input::old('email') }}@endif"
               data-error="{{ trans('error.email') }}"
               required
        >
        <div class="help-block with-errors"></div>
    </div>

    <div class="form-group">
        <label for="selectPartner" class="control-label">{{ trans('order.partner') }}</label>
        {{
           Form::select('partner_id', $partners, isset($record) ? $record->partner_id : null, [
               'placeholder' => trans('partner.select'),
               'id' => 'partnerId',
           ])
        }}
    </div>

    <div class="form-group row">
        <label for="products">{{ trans('product.title') }} - {{ trans('order.quantity') }}</label>
        <div class="product-box">
            @foreach($record->getProducts() as $product)
                <div>{{ $product->name }} - {{ $orderProducts[$product->id]->quantity }}</div>
            @endforeach
        </div>
    </div>

    <div class="form-group row">
        <label for="status">{{ trans('order.status.title') }} </label>
        {{
            Form::select('status', $statuses, isset($record) ? $record->status : null, [
               'placeholder' => trans('order.status.select'),
               'id' => 'status',
           ])
        }}
    </div>

    <div class="form-group row">
        <label for="cost">{{ trans('order.cost') }}</label>
        <input readonly="readonly" value="{{ $record->cost }}"></input>
    </div>
    {!! csrf_field() !!}
    <button type="submit">{{ trans('app.save') }}</button>

</form>

resources/views/order/index.blade.php
<div class="tabs">
    @foreach(\App\Models\Order::getAvailableTypes() as $type)
        @include('elements.order-type-link', ['type' => $type])
    @endforeach
</div>
@if($records->count())
    <div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">{{ trans('order.partner') }}</th>
                <th scope="col">{{ trans('order.cost') }}</th>
                <th scope="col">{{ trans('order.composition') }}</th>
                <th scope="col">{{ trans('order.status.title') }}</th>
                <th scope="col">{{ trans('order.edit') }}</th>
            </tr>
            </thead>
            <tbody>
            @foreach($records as $record)
                <tr>
                    <th scope="row">{{ $record->id }}</th>
                    <td>{{ $record->getPartner()->name }}</td>
                    <td>{{ $record->cost }}</td>
                    <td>{{ $record->composite }}</td>
                    <td>{{ \App\Models\Order::getStatusNameByCode($record->status)}}</td>
                    <td> <a href="{{ route('order.get.edit', ['id' => $record->id]) }}">{{ trans('order.edit') }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <div>
        {{ $records->links() }}
    </div>
@endif

resources/views/weather/index.blade.php
{{ $weather->temp }}